# Generated by Django 4.1.4 on 2022-12-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carford_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Hatch', 'Hatch'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible')], max_length=256)),
                ('color', models.CharField(choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Gray', 'Gray')], max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carford_app.owner')),
            ],
        ),
    ]
