# Generated by Django 4.1.4 on 2022-12-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carford_app', '0003_alter_car_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['owner']},
        ),
    ]
