# Generated by Django 4.1.4 on 2022-12-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carford_app', '0004_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['owner__name']},
        ),
    ]
