# Generated by Django 4.1.4 on 2022-12-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carford_app', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name']},
        ),
    ]
